# Sample RunConfig for use with the RTC-S1 PGE v2.1.0
# This RunConfig should require minimal changes in order to be used with the
# OPERA PCM.

RunConfig:
    # Name for the RunConfig, may be any string
    Name: OPERA-RTC-S1-PGE-SAMPLE-CONFIG

    Groups:
        # PGE-specific RunConfig section
        # This section is only used by the PGE, however, paths to inputs/outputs
        # should align with the similar sections of the SAS RunConfig
        PGE:
            PGENameGroup:
                # Name of the PGE for use with this RunConfig, should always be
                # RTC_S1_PGE when using with the RTC-S1 PGE
                PGEName: RTC_S1_PGE

            InputFilesGroup:
                # List of input files
                # Must be a list containing the path to the input SAFE zip file(s),
                # as well as the path to the Orbit Ephemerides file(s)
                # Paths must correspond to the file system within the Docker container
                InputFilePaths:
                    - /home/rtc_user/input_dir/S1B_IW_SLC__1SDV_20180504T104507_20180504T104535_010770_013AEE_919F.zip
                    - /home/rtc_user/input_dir/S1B_OPER_AUX_POEORB_OPOD_20180524T110543_V20180503T225942_20180505T005942.EOF

            DynamicAncillaryFilesGroup:
                # Map of ancillary file types to paths to the file
                # Paths must correspond to the file system within the Docker container
                AncillaryFileMap:
                    # Path to the Digital Elevation Model
                    # Must be either a single .tif, or a .vrt that points to one
                    # or more .tif files
                    dem_file: /home/rtc_user/input_dir/dem.tif

                    # Burst database, must be an .sqlite3 file
                    burst_database_file: /home/rtc_user/input_dir/burst_db_0.2.0_230831-bbox-only.sqlite

            ProductPathGroup:
                # Path to where output products should be stored
                # Must correspond to the file system within the Docker container,
                # and must have write permissions for the User/Group used with
                # the "Docker run" command
                OutputProductPath: /home/rtc_user/output_dir

                # Path to a scratch directory for the PGE and SAS to store
                # intermediate files that will not be needed after PGE execution
                # completes
                # Must correspond to the file system within the Docker container,
                # and must have write permissions for the User/Group used with
                # the "Docker run" command
                ScratchPath: /home/rtc_user/scratch_dir

            PrimaryExecutable:
                # Identifier for the PGE executable, should always be RTC_S1 for
                # this PGE
                ProductIdentifier: RTC_S1

                # Product version specific to output products
                ProductVersion: "1.0"

                # Path to the executable to run, path must be reachable from
                # within the Docker container (i.e. findable with a "which" command)
                ProgramPath: conda

                # List of command-line options to use with ProgramPath
                ProgramOptions:
                    - run
                    - --no-capture-output
                    - -n
                    - RTC
                    - rtc_s1.py

                # The Error Code base value added to the offset values to make
                # error codes unique per-PGE
                ErrorCodeBase: 300000

                # Path to the Yamale schema used to validate the SAS portion
                # of the RunConfig
                # Path should correspond to the file system within the Docker
                # container, and typically should reference a schema file bundled
                # with the opera_pge installation directory within the container
                # Consult the Docker image build scripts for more info
                SchemaPath: /home/rtc_user/opera/pge/rtc_s1/schema/rtc_s1_sas_schema.yaml

                # Path to the Jinja2 template used to generate the ISO xml
                # metadata file
                # Path should correspond to the file system within the Docker
                # container, and typically should reference a template file bundled
                # with the opera_pge installation directory within the container
                # Consult the Docker image build scripts for more info
                IsoTemplatePath: /home/rtc_user/opera/pge/rtc_s1/templates/OPERA_ISO_metadata_L2_RTC_S1_template.xml.jinja2

                # Date field which designates the point after which the
                # RTC static layer product(s) should be considered valid.
                # This field must be provided for RTC-S1 jobs when static layer
                # generation is enabled (see below), and must be of the form YYYYMMDD
                DataValidityStartDate: 20140403

            QAExecutable:
                # Set to True to enable execution of an additional "Quality Assurance"
                # application after SAS execution has completed
                Enabled: False

                # Path to the executable to run, path must be reachable from
                # within the Docker container (i.e. findable with a "which" command)
                ProgramPath:

                # List of command-line options to use with ProgramPath
                ProgramOptions: []

            DebugLevelGroup:
                # Set to True to enable Debug mode (TODO this is currently a no-op)
                DebugSwitch: False

                # Set to True to have the PGE invoke the SAS/QA executables via
                # a shell, rather than a Python subprocess
                # This allows shell-style syntax to be used in ProgramPath and
                # ProgramOptions, which can be useful for testing
                ExecuteViaShell: False

        # SAS-specific RunConfig section
        # Prior to SAS execution by the PGE, the section below starting at "runconfig"
        # is isolated into its own YAML file for use with the SAS
        SAS:
            runconfig:
                name: rtc_s1_workflow_default

                groups:
                    pge_name_group:
                        pge_name: RTC_S1_PGE

                    input_file_group:
                        # Required. List of SAFE files (min=1)
                        safe_file_path:
                            - /home/rtc_user/input_dir/S1B_IW_SLC__1SDV_20180504T104507_20180504T104535_010770_013AEE_919F.zip
                        # Required. List of orbit (EOF) files (min=1)
                        orbit_file_path:
                            - /home/rtc_user/input_dir/S1B_OPER_AUX_POEORB_OPOD_20180524T110543_V20180503T225942_20180505T005942.EOF
                        # Burst IDs to process. Leave empty to process all bursts.
                        burst_id:
                        # Location from where the source data can be retrieved (URL or DOI)
                        source_data_access: "https://search.asf.alaska.edu/#/?dataset=SENTINEL-1&productTypes=SLC"

                    # This section should match the DynamicAncillaryFilesGroup of the PGE RunConfig
                    dynamic_ancillary_file_group:
                        # Digital elevation model
                        dem_file: /home/rtc_user/input_dir/dem.tif
                        dem_file_description: "Digital Elevation Model (DEM) for the NASA OPERA project version 1.1 (v1.1) based on the Copernicus DEM 30-m and Copernicus 90-m referenced to the WGS84 ellipsoid"

                    static_ancillary_file_group:
                        # burst database sqlite file
                        burst_database_file: /home/rtc_user/input_dir/burst_db_0.2.0_230831-bbox-only.sqlite

                    product_group:
                        product_version: "1.0"

                        # This should match the path used for OutputProductPath
                        product_path: /home/rtc_user/output_dir

                        # This should match the path used for ScratchPath
                        scratch_path: /home/rtc_user/scratch_dir

                        # This should match the path used for OutputProductPath
                        output_dir: /home/rtc_user/output_dir

                        # Validity start date for RTC-S1-STATIC products in the format YYYYMMDD,
                        # This field must be provided for RTC-S1 jobs when static layer
                        # generation is enabled, and should match the value assigned to
                        # DataValidityStartDate above.
                        rtc_s1_static_validity_start_date: 20140403

                        # Location from where the output product can be retrieved (URL or DOI)
                        product_data_access: "https://search.asf.alaska.edu/#/?dataset=OPERA-S1&productTypes=RTC"

                        # RTC-S1 imagery
                        save_bursts: True

                        # Save mosaic of RTC-S1 bursts
                        save_mosaics: False

                        # Save browse image(s)
                        save_browse: True

                        output_imagery_format: COG

                        # Save RTC-S1 metadata in the HDF5 format
                        # Optional for `output_imagery_format` equal to 'ENVI', 'GTiff', or
                        # 'COG', and enabled by default for `output_imagery_format` equal
                        # to 'HDF5' or 'NETCDF' or `save_secondary_layers_as_hdf5` is True
                        save_metadata: True

                    primary_executable:
                        # Must be one of RTC_S1 or RTC_S1_STATIC, this determines the type of
                        # output product created
                        product_type: RTC_S1

                    # SLC processing options
                    # Consult the RTC-S1 SAS User's Guide for more info on each field
                    processing:

                        # Check if ancillary input covers entirely output products
                        check_ancillary_inputs_coverage: True

                        # Polarization channels to process.
                        polarization: dual-pol

                        rtc:
                            output_type: gamma0

                        # OPTIONAL - to provide the number of processes when processing the bursts in parallel
                        # "0" means that the number will be automatically decided based on
                        # the number of cores, `OMP_NUM_THREADS` in environment setting,
                        # and the number of burst to process in runconfig
                        num_workers: 0

                        # OPTIONAL - Mechanism to specify output posting and DEM
                        geocoding:
                            # OPTIONAL - Choices: "single_block", "geogrid", "geogrid_and_radargrid",
                            # and "auto" (default)
                            memory_mode: auto

                            bursts_geogrid:
                                top_left:
                                    x:
                                    y:
                                bottom_right:
                                    x:
                                    y:

                            # Fields to populate the products' metadata required by
                            # CEOS Analysis Ready Data specifications
                            estimated_geometric_accuracy_bias_x: 0.0
                            estimated_geometric_accuracy_bias_y: 0.0
                            estimated_geometric_accuracy_stddev_x: 0.0
                            estimated_geometric_accuracy_stddev_y: 0.0

                        mosaicking:
                            # Mosaic mode - Choices: "average", "first", "bursts_center" (default)
                            mosaic_mode: first
